/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Usuario;
import model.UsuarioDao;
import java.sql.PreparedStatement;
import model.ConectarDao;

/**
 *
 * @author oem
 */
public class formCli extends javax.swing.JFrame {

    /**
     * Creates new form formCli
     */
    public formCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textNome = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textFone = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        cmbSigla = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        textCpf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textEndereco = new javax.swing.JTextField();
        btnexcluir = new javax.swing.JButton();
        btnnovo = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCli = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Usuários");
        setMinimumSize(new java.awt.Dimension(591, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(null);
        jPanel1.add(textNome);
        textNome.setBounds(50, 50, 287, 22);
        jPanel1.add(textEmail);
        textEmail.setBounds(50, 150, 287, 22);

        textFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFoneActionPerformed(evt);
            }
        });
        jPanel1.add(textFone);
        textFone.setBounds(50, 200, 287, 22);

        btnIncluir.setText("Gravar");
        btnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncluirMouseClicked(evt);
            }
        });
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnIncluir);
        btnIncluir.setBounds(395, 258, 87, 55);

        cmbSigla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSiglaItemStateChanged(evt);
            }
        });
        cmbSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSiglaActionPerformed(evt);
            }
        });
        cmbSigla.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cmbSiglaVetoableChange(evt);
            }
        });
        jPanel1.add(cmbSigla);
        cmbSigla.setBounds(373, 147, 119, 22);

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 36, 16);

        jLabel2.setText("Email:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 32, 16);

        jLabel3.setText("Celular:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 180, 40, 16);

        jLabel4.setText("Nível:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(373, 125, 30, 16);

        txtSenha.setText("jPasswordField1");
        jPanel1.add(txtSenha);
        txtSenha.setBounds(50, 310, 113, 22);

        jLabel5.setText("Senha:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 290, 35, 16);

        jLabel6.setText("Repita a Senha:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 290, 80, 16);

        jPasswordField2.setText("jPasswordField1");
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(190, 310, 113, 22);

        jLabel7.setText("Cpf:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 80, 22, 16);

        textCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfActionPerformed(evt);
            }
        });
        jPanel1.add(textCpf);
        textCpf.setBounds(50, 100, 288, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pizza.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 30, 64, 64);

        jLabel9.setText("Endereço:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 230, 60, 16);

        textEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(textEndereco);
        textEndereco.setBounds(50, 250, 287, 22);

        btnexcluir.setText("Excluir");
        btnexcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexcluirMouseClicked(evt);
            }
        });
        jPanel1.add(btnexcluir);
        btnexcluir.setBounds(150, 360, 70, 20);

        btnnovo.setText("Novo");
        btnnovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnovoMouseClicked(evt);
            }
        });
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnovo);
        btnnovo.setBounds(230, 360, 60, 20);

        btnbuscar.setText("Buscar");
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar);
        btnbuscar.setBounds(340, 100, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 505, 392);

        tableCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Celular", "Tipo", "Endereco"
            }
        ));
        jScrollPane1.setViewportView(tableCli);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 398, 493, 187);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFoneActionPerformed
 
    }//GEN-LAST:event_textFoneActionPerformed
    
        private void carregar_usuarios() {
        // método criado para carregar usuaŕios no jtable 
        // do formulário de usuários

        // captura o modelo definido do jtable no formulário de usuários
        DefaultTableModel mytbmodel = (DefaultTableModel) tableCli.getModel();

        // instancia a classe Usuariodao para executar o método buscartodos()
        UsuarioDao u1 = new UsuarioDao();

        // chama o método para buscar todos os registros da tabela usuário
        // armazena dentro de um objeto ResultSet
        ResultSet resul = u1.buscartodos();
        try { 
            
            // apagar todas as linhas do Jtable
            while (tableCli.getModel().getRowCount() > 0) {  
                 ( (DefaultTableModel) tableCli.getModel() ).removeRow(0);  
             } 






// laço para pegar os registros retornadas na ResultSet resul
            
            while (resul.next()) {
                // cria um array para armazenar cada linha com os 4 campos
                // puxados da tabela resul de usuários
                
                Object[] linhas = {resul.getString("cpf"),
                    resul.getString("nome"),
                    resul.getString("email"),
                    resul.getString("celular")};

                // adiciona uma linha de cada vez no jtable de usuaŕios
                mytbmodel.addRow(linhas);
            }

            // posiciona o focus no textcpf 
            this.textCpf.grabFocus();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
        
    }
    
    
    private void btnIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluirMouseClicked
     
        DefaultTableModel MdlTableCli =(DefaultTableModel) tableCli.getModel();
        Object [] linhas = { textNome.getText(),this.textEmail.getText(), 
            this.textFone.getText(), this.cmbSigla.getSelectedItem(),this.textEndereco.getText()};
        
        MdlTableCli.addRow( linhas );
        
        /* Enviar dados para o model Usuario*/
        Usuario u1 = new Usuario();
        u1.setEmail(this.textEmail.getText());
        u1.setCelular(this.textFone.getText());
        u1.setNome(this.textNome.getText());
        u1.setIdNivel ( this.cmbSigla.getSelectedIndex());
        u1.setEndereco(this.textEndereco.getText());
        u1.setCpf(this.textCpf.getText());
        u1.setSenha(this.txtSenha.getText());
        
        UsuarioDao ud = new UsuarioDao();
        ud.incluir(u1);
        
        this.textEmail.setText("");
        this.textFone.setText("");
        this.textNome.setText("");
        this.cmbSigla.setSelectedIndex(0);
        this.textEndereco.setText("");
        
    }//GEN-LAST:event_btnIncluirMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    DefaultComboBoxModel obj =
    (DefaultComboBoxModel) this.cmbSigla.getModel();
     
      obj.removeAllElements();
      obj.addElement("Cliente");
      obj.addElement("Gerente");
      obj.addElement("Operador");
    }//GEN-LAST:event_formWindowOpened

    private void cmbSiglaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSiglaItemStateChanged

      
    }//GEN-LAST:event_cmbSiglaItemStateChanged

    private void cmbSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSiglaActionPerformed
    
    }//GEN-LAST:event_cmbSiglaActionPerformed

    private void cmbSiglaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cmbSiglaVetoableChange
             // TODO add your handling code here:
    }//GEN-LAST:event_cmbSiglaVetoableChange

    private void textCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfActionPerformed

    private void textEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnderecoActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnexcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexcluirMouseClicked

        UsuarioDao u = new UsuarioDao();
        u.excluir(textCpf.getText());
        this.carregar_usuarios();

    }//GEN-LAST:event_btnexcluirMouseClicked

    private void btnnovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnovoMouseClicked
        // preenche todos os campos do formulários usuaŕios com espaços em branco
        this.textCpf.setText("");
        this.textNome.setText("");
        this.textFone.setText("");
        this.textEmail.setText("");
        this.cmbSigla.setSelectedIndex(0);
        this.textCpf.grabFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnnovoMouseClicked

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
        // instancia a classe Usuario model
        Usuario obj = new Usuario();
        // executa o método setcpf para preencher o cpf
        
        obj.setCpf(this.textCpf.getText());

        // instancia o objeto Controller Usariodao
        UsuarioDao u1 = new UsuarioDao();

        // executa o método buscar e coloca os registros dentro 
        // do ResultSet resul 
        ResultSet resul = u1.buscar(obj);
        
        try {
            if (resul.next()) {
                // se o registro foi encontrado preenche os campos do formulário usuários
                this.textNome.setText(resul.getString("nome"));
                this.textEmail.setText(resul.getString("email"));
                this.textFone.setText(resul.getString("celular"));
                this.cmbSigla.setSelectedIndex(resul.getInt("idnivel"));
                this.jPasswordField2.setText(resul.getString("senha"));
            } else {
                JOptionPane.showMessageDialog(null, "Registro não encontrado!");
                this.textCpf.grabFocus();
            }
            
        } catch (SQLException err) {
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnnovo;
    private javax.swing.JComboBox<String> cmbSigla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCli;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textFone;
    private javax.swing.JTextField textNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
